package ec.edu.espe.decisiontree.view;
import com.mongodb.client.MongoCollection;
import ec.edu.espe.decisiontree.view.PnlInventoryAddNewProduct;
import utils.MongoConnection;
import java.awt.BorderLayout;
/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class FrmPrincipalMenuBar extends javax.swing.JFrame {
    private final MongoConnection mongoConnection;
    private static MongoCollection productsCollection;
    private static MongoCollection userCollection;
    private static MongoCollection ordersCollection;
    private static MongoCollection materialsCollection;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public FrmPrincipalMenuBar(){
        mongoConnection = MongoConnection.getInstance();
        userCollection = mongoConnection.getCollection("User"); 
        productsCollection = mongoConnection.getCollection("Products");
        ordersCollection = mongoConnection.getCollection("Orders");
        materialsCollection = mongoConnection.getCollection("Materials");
        initComponents();
        initPnlStartPage();
    }
    
    private void initPnlStartPage(){
        PnlInventoryAddNewProduct pnlStartPage = new PnlInventoryAddNewProduct(productsCollection);
        pnlStartPage.setSize(980,540);
        pnlStartPage.setLocation(0,0);
        PnlWindow.removeAll();
        PnlWindow.add(pnlStartPage, BorderLayout.CENTER);
        PnlWindow.revalidate();
        PnlWindow.repaint();
    }
//    private void initPnlAbout(){
//        PnlAbout pnlAbout = new PnlAbout();
//        pnlAbout.setSize(932,525);
//        pnlAbout.setLocation(20,0);
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlAbout, BorderLayout.CENTER);
//        PnlWindow.revalidate();
//        PnlWindow.repaint();
//    }
//    
//    private void initPnlContactUs(){
//        PnlContactUs pnlContactUs = new PnlContactUs();
//        pnlContactUs.setSize(980,523);
//        pnlContactUs.setLocation(0,0);
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlContactUs, BorderLayout.CENTER);
//        PnlWindow.revalidate();
//        PnlWindow.repaint();
//    }
//    private void initPnlProfile(){
//        PnlProfile pnlProfile = new PnlProfile(userCollection, this);
//        pnlProfile.setSize(980,629);
//        pnlProfile.setLocation(0,0);
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlProfile, pnlProfile);
//        PnlWindow.revalidate();
//        PnlWindow.repaint(); 
//    }
//    private void initPnlAgenda(){
//        PnlAgenda pnlAgenda = new PnlAgenda(ordersCollection);
//        pnlAgenda.setSize(980,629);
//        pnlAgenda.setLocation(0,0);
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlAgenda, pnlAgenda);
//        PnlWindow.revalidate();
//        PnlWindow.repaint();    
//    }
//   
//    private void initPnlInventory(){
//        PnlInventory pnlInventory = new PnlInventory(productsCollection, materialsCollection, userCollection);
//        pnlInventory.setSize(996, 623);
//        pnlInventory.setLocation(0,0);
//        
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlInventory, BorderLayout.CENTER);
//        PnlWindow.revalidate();
//        PnlWindow.repaint();    
//    }
//    public void initOrganizer()
//    {
//        PnlOrganizer pnlOrganizer = new PnlOrganizer(materialsCollection);
//        pnlOrganizer.setSize(980, 629);
//        pnlOrganizer.setLocation(0,0);
//        
//        PnlWindow.removeAll();
//        PnlWindow.add(pnlOrganizer, BorderLayout.CENTER);
//        PnlWindow.revalidate();
//        PnlWindow.repaint();
//             
//    }
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlWindow = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnEHA = new javax.swing.JMenu();
        mnuActions = new javax.swing.JMenu();
        mnuInventory = new javax.swing.JMenuItem();
        MnHelp = new javax.swing.JMenu();
        mnuContactUs = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlWindow.setBackground(new java.awt.Color(255, 255, 255));
        PnlWindow.setMaximumSize(new java.awt.Dimension(980, 629));
        PnlWindow.setMinimumSize(new java.awt.Dimension(980, 629));
        PnlWindow.setPreferredSize(new java.awt.Dimension(980, 629));

        javax.swing.GroupLayout PnlWindowLayout = new javax.swing.GroupLayout(PnlWindow);
        PnlWindow.setLayout(PnlWindowLayout);
        PnlWindowLayout.setHorizontalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        PnlWindowLayout.setVerticalGroup(
            PnlWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));

        MnEHA.setText("Entre Hilos & Algodon");
        MnEHA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnEHA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnEHAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MnEHAMousePressed(evt);
            }
        });
        MnEHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEHAActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnEHA);

        mnuActions.setText("Actions");
        mnuActions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuActionsMouseClicked(evt);
            }
        });

        mnuInventory.setText("Inventory");
        mnuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuInventoryMousePressed(evt);
            }
        });
        mnuActions.add(mnuInventory);

        jMenuBar1.add(mnuActions);

        MnHelp.setText("Help");
        MnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuContactUs.setText("Contact Us");
        mnuContactUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuContactUsMousePressed(evt);
            }
        });
        MnHelp.add(mnuContactUs);

        mnuAbout.setText("About Entre Hilos & Algodón Management Software");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuAboutMousePressed(evt);
            }
        });
        MnHelp.add(mnuAbout);

        jMenuBar1.add(MnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnEHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEHAActionPerformed
        
    }//GEN-LAST:event_MnEHAActionPerformed

    private void MnEHAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnEHAMouseClicked

    }//GEN-LAST:event_MnEHAMouseClicked

    private void mnuActionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuActionsMouseClicked

        
    }//GEN-LAST:event_mnuActionsMouseClicked

    private void mnuInventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInventoryMousePressed
//         initPnlInventory();
    }//GEN-LAST:event_mnuInventoryMousePressed

    private void mnuAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMousePressed
//       initPnlAbout();
    }//GEN-LAST:event_mnuAboutMousePressed

    private void MnEHAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnEHAMousePressed
//        initPnlStartPage();
    }//GEN-LAST:event_MnEHAMousePressed

    private void mnuContactUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContactUsMousePressed
//       initPnlContactUs();
    }//GEN-LAST:event_mnuContactUsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalMenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnEHA;
    private javax.swing.JMenu MnHelp;
    private javax.swing.JPanel PnlWindow;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuActions;
    private javax.swing.JMenuItem mnuContactUs;
    private javax.swing.JMenuItem mnuInventory;
    // End of variables declaration//GEN-END:variables
}
